version: "3.5"
services:
  loginserver:
    build: ./Server
    command:  bash -c "npm install; nodemon login.js --color=always"
    ports:
     - "8085:8080"
    volumes:
     - ./Server:/usr/src/app
    networks:
     - mongo_gabriela
     - rabbitmq_gama
  loginclient:
    build: ./Client
    command:  bash -c "npm install; nodemon client_login.js --color=always"
    ports:
     - "8086:8080"
    volumes:
     - ./Client:/usr/src/app
    networks:
     - mongo_gabriela
     - rabbitmq_gama

networks:
  mongo_gabriela:
    external:
      name: my_network
  rabbitmq_gama:
    external:
      name: my_network_gama
