version: "3.5"
services:
  loginmicroservice:
    build: .
    command:  bash -c "npm install; nodemon app.js --color=always"
    ports:
     - "8083:8080"
     - "5859:5858"
    volumes:
     - ./app:/usr/src/app
    networks:
     - mongo_gabriela
     - rabbitmq_gama

networks:
  mongo_gabriela:
    external:
      name: my_network
  rabbitmq_gama:
    external:
      name: my_network_gama
