version: "3.5"
services:
  userserver:
    build: ./Server
    command:  bash -c "npm install; nodemon user.js --color=always"
    ports:
     - "8080:8080"
    volumes:
     - ./Server:/usr/src/app
    networks:
     - mongo_gabriela
     - rabbitmq_gama

  userclient:
    build: ./Client
    command:  bash -c "npm install; nodemon client_user.js --color=always"
    ports:
     - "8083:8080"
    volumes:
     - ./Client:/usr/src/app
    networks:
     - mongo_gabriela
     - rabbitmq_gama

networks:
  mongo_gabriela:
    external:
      name: my_network
  rabbitmq_gama:
    external:
      name: my_network_gama
